#To build:
#$ docker-compose build
#To run:
#$ docker-compose up
services:
  kalilinux:   
    #hostname: kalilinux.lab #only declare hostname when using network_mode=host
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME:-kali} #Override default `kali` by setting $USERNAME environment variable
        PASSWORD: ${PASSWORD:-kalilinux} #Override default `kalilinux` by setting $PASSWORD environment variable
        KALISHELL: /bin/bash
        NOVNCPORT: ${NOVNCPORT:-8080}
        VNCPORT: ${VNCPORT:-5901}
        SSHPORT: ${SSHPORT:-2222}
    image: 'jhu-information-security-institute/netsec-kalilinux-docker:${VERSION:-latest}' #Override default `latest` by setting $VERSION environment variable
    restart: always
    cap_add:
      - NET_ADMIN
    ############################################################
    #either use mapped ports or network_mode=host, not both
    #ports:
    #  - 0.0.0.0:8080:8080
    network_mode: host
    ############################################################
    environment:
      - USER=${USERNAME:-kali} #Override default `kali` by setting $USERNAME environment variable
      - PASSWORD=${PASSWORD:-kalilinux} #Override default `kalilinux` by setting $PASSWORD environment variable
      - SHELL=${KALISHELL:-/bin/bash}
      - NOVNCPORT=${NOVNCPORT:-8080}
      - VNCPORT=${VNCPORT:-5901} 
      - SSHPORT=${SSHPORT:-2222}
    volumes:
      - /mnt/dockershared:/mnt/dockershared #Available on host in /mnt/dockershared
    entrypoint: ["/bin/bash", "/startup.sh"]

volumes:
  data: {}
